'use client';

import { useState } from 'react';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { auth, db } from '@/lib/firebase';
import { doc, setDoc, serverTimestamp, collection } from 'firebase/firestore';
import { useRouter } from 'next/navigation';
import { User, Restaurant } from '@/lib/types';
import Link from 'next/link';

export default function RegisterPage() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [restaurantName, setRestaurantName] = useState('');
    const [ownerName, setOwnerName] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const router = useRouter();

    const handleRegister = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            // 1. Create Auth User
            const userCredential = await createUserWithEmailAndPassword(auth, email, password);
            const user = userCredential.user;

            // 2. Create Restaurant ID (auto-generated by Firestore or slug)
            // Let's use a random ID or the user ID prefix for simplicity in MVP, 
            // but better to let Firestore generate.
            const restaurantRef = doc(collection(db, 'restaurants')); // Auto-ID
            const restaurantId = restaurantRef.id;

            // 3. Create Restaurant Doc
            const newRestaurant: Restaurant = {
                id: restaurantId,
                name: restaurantName,
                ownerId: user.uid,
                createdAt: Date.now(),
                currency: 'PEN', // Default
            };
            await setDoc(restaurantRef, newRestaurant);

            // 4. Create User Profile
            const newUserProfile: User = {
                uid: user.uid,
                email: user.email,
                displayName: ownerName,
                role: 'owner',
                restaurantId: restaurantId
            };
            await setDoc(doc(db, 'users', user.uid), newUserProfile);

            // 5. Redirect
            router.push('/admin');

        } catch (err: any) {
            console.error(err);

            // Handle "Zombie" account (Auth created, but Firestore failed previously)
            if (err.code === 'auth/email-already-in-use') {
                try {
                    // 1. Try to Login
                    const { signInWithEmailAndPassword } = await import('firebase/auth');
                    const userCredential = await signInWithEmailAndPassword(auth, email, password);
                    const user = userCredential.user;

                    // 2. Check if Firestore profile exists
                    const { doc, getDoc, setDoc, collection } = await import('firebase/firestore');
                    const userDoc = await getDoc(doc(db, 'users', user.uid));

                    if (!userDoc.exists()) {
                        // 3. Resume Creation (Recovery Mode)
                        const restaurantRef = doc(collection(db, 'restaurants'));
                        const restaurantId = restaurantRef.id;

                        const newRestaurant: Restaurant = {
                            id: restaurantId,
                            name: restaurantName,
                            ownerId: user.uid,
                            createdAt: Date.now(),
                            currency: 'PEN',
                        };
                        await setDoc(restaurantRef, newRestaurant);

                        const newUserProfile: User = {
                            uid: user.uid,
                            email: user.email,
                            displayName: ownerName,
                            role: 'owner',
                            restaurantId: restaurantId
                        };
                        await setDoc(doc(db, 'users', user.uid), newUserProfile);

                        router.push('/admin');
                        return;
                    } else {
                        // Account fully exists, just redirect
                        router.push('/admin');
                        return;
                    }
                } catch (recoveryErr) {
                    // Password might be wrong or other issue
                    setError('El correo ya existe. Intenta iniciar sesión o usa otro.');
                }
            } else {
                setError(err.message || 'Error al registrar.');
            }
        } finally {
            setLoading(false);
        }
    };



    return (
        <div className="flex items-center justify-center min-h-screen bg-slate-950 text-white p-4">
            <div className="w-full max-w-md p-8 bg-slate-900 rounded-2xl shadow-xl border border-slate-800">
                <h1 className="text-3xl font-bold mb-2 text-center text-blue-500">RestoFast SaaS</h1>
                <p className="text-slate-400 text-center mb-6">Registra tu Restaurante</p>

                {error && (
                    <div className="bg-red-500/10 border border-red-500 text-red-500 p-3 rounded mb-4 text-sm">
                        {error}
                    </div>
                )}

                <form onSubmit={handleRegister} className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium mb-1 text-slate-400">Nombre del Restaurante</label>
                        <input
                            type="text"
                            required
                            value={restaurantName}
                            onChange={(e) => setRestaurantName(e.target.value)}
                            className="w-full p-3 rounded bg-slate-950 border border-slate-800 focus:border-blue-500 outline-none"
                            placeholder="Ej: El Buen Sabor"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium mb-1 text-slate-400">Tu Nombre (Dueño)</label>
                        <input
                            type="text"
                            required
                            value={ownerName}
                            onChange={(e) => setOwnerName(e.target.value)}
                            className="w-full p-3 rounded bg-slate-950 border border-slate-800 focus:border-blue-500 outline-none"
                            placeholder="Ej: Juan Pérez"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium mb-1 text-slate-400">Email</label>
                        <input
                            type="email"
                            required
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className="w-full p-3 rounded bg-slate-950 border border-slate-800 focus:border-blue-500 outline-none"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium mb-1 text-slate-400">Contraseña</label>
                        <input
                            type="password"
                            required
                            minLength={6}
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-full p-3 rounded bg-slate-950 border border-slate-800 focus:border-blue-500 outline-none"
                        />
                    </div>

                    <button
                        type="submit"
                        disabled={loading}
                        className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded shadow-lg transition-all"
                    >
                        {loading ? 'Creando cuenta...' : 'Registrar mi Negocio'}
                    </button>

                    <div className="text-center mt-4">
                        <Link href="/login" className="text-sm text-slate-500 hover:text-white transition">
                            ¿Ya tienes cuenta? Inicia Sesión
                        </Link>
                    </div>
                </form>
            </div>
        </div>
    );
}
