'use client';

import { useState } from 'react';
import { createUserWithEmailAndPassword } from 'firebase/auth';
import { auth, db } from '@/lib/firebase';
import { doc, setDoc, serverTimestamp, collection } from 'firebase/firestore';
import { useRouter } from 'next/navigation';
import { User, Restaurant } from '@/lib/types';
import Link from 'next/link';
import { UtensilsCrossed, ChefHat, ArrowRight, Loader2, Store, User as UserIcon } from 'lucide-react';

export default function RegisterPage() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [restaurantName, setRestaurantName] = useState('');
    const [ownerName, setOwnerName] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const router = useRouter();

    const handleRegister = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            // 1. Create Auth User
            const userCredential = await createUserWithEmailAndPassword(auth, email, password);
            const user = userCredential.user;

            // 2. Create Restaurant ID (auto-generated by Firestore or slug)
            // Let's use a random ID or the user ID prefix for simplicity in MVP, 
            // but better to let Firestore generate.
            const restaurantRef = doc(collection(db, 'restaurants')); // Auto-ID
            const restaurantId = restaurantRef.id;

            // 3. Create Restaurant Doc
            const newRestaurant: Restaurant = {
                id: restaurantId,
                name: restaurantName,
                ownerId: user.uid,
                createdAt: Date.now(),
                currency: 'PEN', // Default
                theme: 'dark',
                paymentMethods: []
            };
            await setDoc(restaurantRef, newRestaurant);

            // 4. Create User Profile
            const newUserProfile: User = {
                uid: user.uid,
                email: user.email,
                displayName: ownerName,
                role: 'owner',
                restaurantId: restaurantId
            };
            await setDoc(doc(db, 'users', user.uid), newUserProfile);

            // 5. Redirect
            router.push('/admin');

        } catch (err: any) {
            console.error(err);

            // Handle "Zombie" account (Auth created, but Firestore failed previously)
            if (err.code === 'auth/email-already-in-use') {
                try {
                    // 1. Try to Login
                    const { signInWithEmailAndPassword } = await import('firebase/auth');
                    const userCredential = await signInWithEmailAndPassword(auth, email, password);
                    const user = userCredential.user;

                    // 2. Check if Firestore profile exists
                    const { doc, getDoc, setDoc, collection } = await import('firebase/firestore');
                    const userDoc = await getDoc(doc(db, 'users', user.uid));

                    if (!userDoc.exists()) {
                        // 3. Resume Creation (Recovery Mode)
                        const restaurantRef = doc(collection(db, 'restaurants'));
                        const restaurantId = restaurantRef.id;

                        const newRestaurant: Restaurant = {
                            id: restaurantId,
                            name: restaurantName,
                            ownerId: user.uid,
                            createdAt: Date.now(),
                            currency: 'PEN',
                            theme: 'dark',
                            paymentMethods: []
                        };
                        await setDoc(restaurantRef, newRestaurant);

                        const newUserProfile: User = {
                            uid: user.uid,
                            email: user.email,
                            displayName: ownerName,
                            role: 'owner',
                            restaurantId: restaurantId
                        };
                        await setDoc(doc(db, 'users', user.uid), newUserProfile);

                        router.push('/admin');
                        return;
                    } else {
                        // Account fully exists, just redirect
                        router.push('/admin');
                        return;
                    }
                } catch (recoveryErr) {
                    // Password might be wrong or other issue
                    setError('El correo ya existe. Intenta iniciar sesión o usa otro.');
                }
            } else {
                setError(err.message || 'Error al registrar.');
            }
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="flex items-center justify-center min-h-screen bg-slate-950 text-white p-4 relative overflow-hidden">

            {/* Background Decorations */}
            <div className="absolute top-[-10%] right-[-10%] w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />
            <div className="absolute bottom-[-10%] left-[-10%] w-96 h-96 bg-orange-600/10 rounded-full blur-3xl pointer-events-none" />

            <div className="w-full max-w-md p-8 bg-slate-900/80 backdrop-blur-xl rounded-2xl shadow-2xl border border-slate-800 relative z-10 animate-in fade-in zoom-in-95 duration-500">

                {/* Brand Header */}
                <div className="flex flex-col items-center mb-8">
                    <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-2xl flex items-center justify-center shadow-lg shadow-blue-500/20 mb-4 transform -rotate-3">
                        <Store size={32} className="text-white" />
                    </div>
                    <h1 className="text-3xl font-black tracking-tight text-white mb-1">
                        Nuevo <span className="text-blue-500">Restaurante</span>
                    </h1>
                    <p className="text-slate-400 text-sm font-medium">Comienza a digitalizar tu negocio hoy</p>
                </div>

                {error && (
                    <div className="bg-red-500/10 border border-red-500/50 text-red-400 p-3 rounded-lg mb-6 text-sm flex items-center gap-2 animate-in shake">
                        <span>⚠️</span>
                        {error}
                    </div>
                )}

                <form onSubmit={handleRegister} className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1">
                            <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider ml-1">Restaurante</label>
                            <input
                                type="text"
                                required
                                value={restaurantName}
                                onChange={(e) => setRestaurantName(e.target.value)}
                                className="w-full p-3 rounded-xl bg-slate-950 border border-slate-700/50 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none transition-all placeholder:text-slate-600 text-slate-200"
                                placeholder="Ej: Pollería..."
                            />
                        </div>

                        <div className="space-y-1">
                            <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider ml-1">Dueño</label>
                            <input
                                type="text"
                                required
                                value={ownerName}
                                onChange={(e) => setOwnerName(e.target.value)}
                                className="w-full p-3 rounded-xl bg-slate-950 border border-slate-700/50 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none transition-all placeholder:text-slate-600 text-slate-200"
                                placeholder="Ej: Juan..."
                            />
                        </div>
                    </div>

                    <div className="space-y-1">
                        <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider ml-1">Email</label>
                        <input
                            type="email"
                            required
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className="w-full p-3 rounded-xl bg-slate-950 border border-slate-700/50 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none transition-all placeholder:text-slate-600 text-slate-200"
                            placeholder="correo@ejemplo.com"
                        />
                    </div>
                    <div className="space-y-1">
                        <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider ml-1">Contraseña</label>
                        <input
                            type="password"
                            required
                            minLength={6}
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-full p-3 rounded-xl bg-slate-950 border border-slate-700/50 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none transition-all placeholder:text-slate-600 text-slate-200"
                            placeholder="••••••"
                        />
                    </div>

                    <button
                        type="submit"
                        disabled={loading}
                        className="w-full py-4 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-bold rounded-xl shadow-lg shadow-blue-900/20 transition-all active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2 mt-4"
                    >
                        {loading ? (
                            <>
                                <Loader2 size={20} className="animate-spin" />
                                Creando...
                            </>
                        ) : (
                            <>
                                Registrar mi Negocio <ArrowRight size={20} />
                            </>
                        )}
                    </button>

                    <div className="text-center mt-6 pt-4 border-t border-slate-800">
                        <Link href="/login" className="text-sm text-slate-500 hover:text-white transition font-medium">
                            ¿Ya tienes cuenta? <span className="text-blue-400">Inicia Sesión</span>
                        </Link>
                    </div>
                </form>
            </div>
        </div>
    );
}
